### ISSUE TITLE
What are the best practices for organizing CSS?

### ISSUE THREAD

**Issue by YuriyOborozhnyi** [animegungrave/hugo-knowledge-base-theme#21]
Hey guys, the questions are pretty dumb and straightforward, however I have a lack of experience working on HTML & CSS, and I also would like us to discuss the approaches, so:

- How should we organize content _inside_ the CSS files?
- How should we organize CSS files (one per template or so)?
- What are the best practices for this topic?
- Should we use SASS or SCSS or something instead?

Let's talk.

**Comment by alexander-derevyanko** [comment]
1. As for me I prefer use SCSS in the most cases. The differencies between SASS & SCSS are quite simple: SASS  is more syntax oriented and quite similar to CSS. Please take a look [example](https://sass-lang.com/documentation/syntax)
1. Concerning files organization: it'd be better to have some entry point like `main.scss` where the rest of the files will be imported. Please take a look this [organization](https://medium.com/@dannyhuang_75970/sass-project-structure-for-big-projects-8c4a740846ee)
1. If you interested in CSS methodologies also take a [look](https://travelscode.com/css-metodologiyi/)

**Comment by YuriyOborozhnyi** [comment]
Thanks @alexander-derevyanko. I checked all the resources you mentioned, they were helpful. Appreciate it.

I also read some articles on LESS vs SASS (SCSS) and so on, so I think we can go with SCSS since we both are agree. This point could be considered as resolved.

I will dig into the styles structure more the following days and let you know.

**Comment by alexander-derevyanko** [comment]
@YuriyOborozhnyi I believe that we've already decided on the styling approach that we'll follow, so current issue should be closed.

**Comment by YuriyOborozhnyi** [comment]
@alexander-derevyanko, agree, closing it. Thank you for participating in the discussion.
