### ISSUE TITLE
Organize SCSS structure for the Hugo theme

### ISSUE THREAD

**Issue by YuriyOborozhnyi** [animegungrave/hugo-knowledge-base-theme#24]
## User Story

_As a Hugo developer,_
_I want my `.scss` files to be organized,_
_so we'll avoid mess and have a well-structured project outline._

## Requirements

* Think about the well-structured outline for style files specifically _for Hugo_ sites/themes.
I encourage you to check how other people achieve it for their Hugo projects. You can also seek for non-Hugo sites structure for the ideas.
* Create `.scss` style files even if they are empty to show how your folder/files structure will look like.
* Rewrite [`styles.css`](https://github.com/animegungrave/hugo-knowledge-base-theme/pull/22/files#diff-a16a51aaea7dc21d3202074fc7228024) from #22 pull request to well-aligned `.scss` format.

## Open Questions

- [x] Where are we going to store `.scss` files for Hugo theme?
  - [x] Is `static` folder good enough for this purpose? - No, [as it's stated](https://gohugo.io/content-management/static-files/), these files cannot be processed.
  - [x] What about [`assets`](https://github.com/alex-shpak/hugo-book/tree/1941d71/assets) folder?
  - [ ] Can we store `.scss` along with the target `.html` template like Angular projects do? Do we need this approach really?
- [x] Is it a good idea to have `.scss` per template (per `single.html`, `list.html`, `baseof.html`, any partial template, etc.) or not?

**Comment by YuriyOborozhnyi** [comment]
Please, whoever is going to take this ticket, share your thoughts and your design on folder's structure _before_ implementing it, so we can discuss and approve the approach. Thanks.

**Comment by alexander-derevyanko** [comment]
1. I guess, we need to store our stylesheets in the `assets` folder. It'd be better to use `static` folder for storing some images or `json` files. This is more suitable for `HUGO` approach.
1. When designing the SCSS folder structure, I based on this approach:
![scss](https://user-images.githubusercontent.com/21138225/70391038-5c93a900-19d9-11ea-80f3-a7c0a2ce0c40.png)

1. According to `.scss` per template, I've created `pages` folder.

**Comment by YuriyOborozhnyi** [comment]
Hi @alexander-derevyanko, thank you for bringing this here. I like the structure you propose, however I feel that Hugo is a bit different case, so we could try to adjust the structure specifically for Hugo sites.

My point here is that we could mimic Hugo's `layout` structure like [it's usually done for unit tests](http://www.tysoncadenhead.com/blog/where-should-i-put-javascript-unit-tests/).

So we could end up with the following structure:

```
scss/
|- abstracts/
|     |- _variables.scss
|     `- index.scss
|- layouts/          # here we start to mimic Hugo site
|     |- _default/
|     |     |- _baseof.scss
|     |     |- _list.scss
|     |     |- _single.scss
|     |     `- index.scss
|     |- partials/
|     |     |- _content-tree.scss
|     |     |- _footer.scss
|     |     |- _head.scss
|     |     |- _header.scss
|     |     |- _toc.scss
|     |     |- ...
|     |     `- index.scss 
|     |- 404.scss
|     |- home.scss    # we should rename our index.html?
|     `- index.scss
|- # other folders later e.g. components, etc.
`- main.scss
```

I think it's also a great idea to group our `partials` later into relevant sub-ground later in the future.

**Comment by alexander-derevyanko** [comment]
Conserning your propostion - it sounds good, however I have several concerns:

- I guess we need to start development with basic structure without too much spliting to avoid premature optimization on the first step, it can be done later;
- I am not sure that we need strictly follow Hugo-specific site structure when orginize our `stylesheets`. Such structure may in the end be redundant for this theme.
- In your specific example `_default` folder will be redundant. Most of the `scss` files will be contain repeating styles. We need to organize a structure that follows `DRY` principle.

**Comment by YuriyOborozhnyi** [comment]
Just a note: we decided to go w/ mimicking the layout's structure for SCSS files as [it's being proposed](https://github.com/animegungrave/hugo-knowledge-base-theme/issues/24#issuecomment-564235818).
