### ISSUE TITLE
Investigate free hosting options for Hugo sites

### ISSUE THREAD

**Issue by YuriyOborozhnyi** [animegungrave/hugo-knowledge-base-theme#6]
## Motivation

We need at least 2 sites being deployed:

1. Project site with development notes and all useful information to share.
It should be based on any stable and useful theme, since it's our living resources for sharing ideas, items and so on.
2. Test site for playing around with our theme.
We need a test site (`exampleSite` or separate repo? - TBD) which is based on our theme, so we can easily test all the changes we make there.

## Background

I tried to use GitHub Pages (see [animegungrave.github.io repo](https://github.com/animegungrave/animegungrave.github.io)) for hosting project development notes, however I cannot add one more GitHub Pages repo for this organization.

We could set GitHub Pages to the project-level or just use any of our profile for this purpose, however I believe we should investigate different hosting options, particularly because GitHub pages are good for Jekyll SSG sites and aren't aimed to store output html files. Since we're using Hugo, we treat GitHub Pages repo as a container of artifacts, which smells a bit bad for me.

## Requirements

Please investigate the solutions for hosting sites (especially Hugo sites) and prepare short comparison results.

* Hosting should be quick and reliable.
* Hosting should be free.
  * I assume we need to have unlimited (or so) number of deployments.

## Useful Links

* [Hugo Hosting & Deployment](https://gohugo.io/hosting-and-deployment/)

**Comment by YuriyOborozhnyi** [comment]
It feels like [Render.com](https://gohugo.io/hosting-and-deployment/hosting-on-render/) is suitable option.

See https://render.com/pricing

What do you @alexander-derevyanko, @Vitaliy-Dob guys think?

**Comment by alexander-derevyanko** [comment]
I have checked several hostings. According to free plan almost all options have the same set of offers. I have stayed on these ones: [Render](https://render.com/pricing), Firebase and [Zeit](https://zeit.co/pricing). Please take a look, guys.

**Comment by YuriyOborozhnyi** [comment]
Actually we can host it anywhere. We just need a free machine accessible from the Internet. That's it.

I agree Render is a good option. [This guide](https://gohugo.io/hosting-and-deployment/hosting-on-render/) illustrates quite good that CI/CD is possible and even pretty easy.

However, I'm not sure if we can make customize it the way to deploy site from `exampleSite` folder.

**Comment by YuriyOborozhnyi** [comment]
Ah, no, seems we actually _can_. As [Deploy Hooks](https://render.com/docs/deploy-hooks) page states, we can even execute the shell script to do custom work.

**Comment by YuriyOborozhnyi** [comment]
@alexander-derevyanko, let's try to set up CI/CD for our [docs](https://github.com/animegungrave/docs) repo first, since it should be easy one. If we are fine w/ it, we'll create `exampleSite` and put it to Render too.

**Comment by YuriyOborozhnyi** [comment]
@alexander-derevyanko, I've invited you to Render. Please check your mailbox.

**Comment by YuriyOborozhnyi** [comment]
@alexander-derevyanko, do you want to play w/ setting up integration w/ Render for [docs](https://github.com/animegungrave/docs) repo?

**Comment by alexander-derevyanko** [comment]
@YuriyOborozhnyi invitation has been accepted. Yeah, I guess it will be quiet interesting. Will do it

**Comment by YuriyOborozhnyi** [comment]
@alexander-derevyanko, sweet. I've created animegungrave/docs#1 issue for this purpose. You can start working on it whenever you have time.

Once it's done and we are satisfied w/ the results, we can set up a deployment for this repository for `exampleSite` (see #9).

**Comment by anurag** [comment]
Render founder here (I got a notification for this thread).

Great to see y'all trying this out, and happy to help with anything you might need!

**Comment by YuriyOborozhnyi** [comment]
Nice to meet you, @anurag. Thank your for being so friendly 😊.

**Comment by YuriyOborozhnyi** [comment]
I think we're done here for now, closing this ticket.
